model_list:
  - model_name:  grok-3-mini
    litellm_params:
      model: azure/grok-3-mini
      api_base: "${AZURE_BASE_URL}"
      api_key: "${AZURE_API_KEY}"
    guardrails:
      - guardrail_name: "panw-prisma-airs-guardrail"
        litellm_params:
          guardrail: panw_prisma_airs
          mode: "pre_call"  # Or "post_call"
          api_key: "${AIRS_API_KEY}"
          profile_name: "${AIRS_DEFAULT_PROFILE_NAME}"
          api_base: "${AIRS_API_URL}"

# NOTE: It may be a good idea to comment out "success_callback", "cache", "cache_params" (both lines under) when you first start until this works!
litellm_settings:
  success_callback: ["langfuse"]
  cache: True
  cache_params:
    type: "redis"
    supported_call_types: ["acompletion", "completion", "embedding", "aembedding"]
general_settings:
  master_key: sk-1234