model_list:
  - model_name:  grok-3-mini
    litellm_params:
      model: azure/grok-3-mini
      api_base: "${AZURE_BASE_URL}"
      api_key: "${AZURE_API_KEY}"
    guardrails:
      - guardrail_name: "panw-prisma-airs-guardrail"
        litellm_params:
          guardrail: panw_prisma_airs
          mode: "pre_call"  # Or "post_call"
          api_key: "${AIRS_API_KEY}"
          profile_name: "${AIRS_DEFAULT_PROFILE_NAME}"
          api_base: "${AIRS_API_URL}"

# General settings
litellm_settings:
  drop_params: true
  set_verbose: true
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

# Router settings
router_settings:
  routing_strategy: simple-shuffle
  model_group_alias:
    grok-3-mini: grok-3-mini
  num_retries: 3
  timeout: 300
  redis_host: null
  redis_password: null
  redis_port: null
  enable_pre_call_checks: true

# Environment variables
environment_variables:
  LITELLM_LOG: INFO
  STORE_MODEL_IN_DB: "True"